on:
  pull_request:
    types:
      - opened

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: DEV
    defaults:
      run:
        shell: bash

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1

    - name: 'Create Terraform Plan Artifact for Apply'
      run: |
        sudo apt-get install jq moreutils
        terraform init -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -backend-config="region=${{ secrets.AWS_REGION }}" \
          -backend-config="bucket=${{ secrets.BUCKET }}" \
          -backend-config="key=${{ secrets.KEY }}" \
          -backend-config="dynamodb_table=${{ secrets.DYNAMODB_TABLE }}" \
          -backend-config="encrypt=${{ secrets.BACKEND_ENCRYPT }}"
        jq '.aws_region = "${{ secrets.AWS_REGION }}"' variables.tfvars.json|sponge variables.tfvars.json
        jq '.aws_replica_region = "${{ secrets.AWS_REPLICA_REGION }}"' variables.tfvars.json|sponge variables.tfvars.json
        jq '.aws_region_code = "${{ secrets.AWS_REGION_CODE }}"' variables.tfvars.json|sponge variables.tfvars.json
        jq '.aws_replica_region_code = "${{ secrets.AWS_REPLICA_REGION_CODE }}"' variables.tfvars.json|sponge variables.tfvars.json
        jq '.aws_team = "${{ secrets.AWS_TEAM }}"' variables.tfvars.json|sponge variables.tfvars.json
        jq '.tag_automation = "${{ secrets.TAG_AUTOMATION }}"' variables.tfvars.json|sponge variables.tfvars.json
        jq '.tag_env = "${{ secrets.ENVIRONMENT }}"' variables.tfvars.json|sponge variables.tfvars.json
        jq '.tag_framework = "${{ secrets.TAG_FRAMEWORK }}"' variables.tfvars.json|sponge variables.tfvars.json
        jq '.tag_owner = "${{ secrets.TAG_OWNER }}"' variables.tfvars.json|sponge variables.tfvars.json
        jq '.tag_prefix = "${{ secrets.TAG_PREFIX }}"' variables.tfvars.json|sponge variables.tfvars.json
        jq '.tag_support_group = "${{ secrets.TAG_SUPPORT_GROUP }}"' variables.tfvars.json|sponge variables.tfvars.json
        export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
        export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        export AWS_DEFAULT_REGION="${{ secrets.AWS_REGION }}"
        terraform init
        terraform plan -out src/tfplan

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: TerraformPlan
        path: src/tfplan
        retention-days: 1